version: '3'

networks:
  sp_int:


volumes:
  postgres_data:
    driver: local
  keycloak-theme:
    driver: local
  pgadmin_data:
    driver: local

services:
  postgres:
    container_name: pgsql
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    networks:
      - sp_int

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSW}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sp_int

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    volumes:
      - keycloak-theme:/opt/jboss/keycloak/themes
    env_file:
      - .env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      KEYCLOAK_USER: ${IDP_MASTER_USER}
      KEYCLOAK_PASSWORD: ${IDP_MASTER_PASS}
    ports:
      - 8082:8080
    depends_on:
      - postgres
    networks:
      - sp_int

  nginx:
    image: nginx:1.25.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - keycloak
    networks:
      - sp_int

  node:
    build:
      context: ./server
    image: nodeimage
    container_name: sp_node
    ports:
      - "8081:8081"
    networks:
      - sp_int
